_target_: aibedo_salva.models.unet.SphericalUNet

defaults:
  - _self_
  - base_model_config.yaml   # general, model independent, parameters
  - /input_transform: none.yaml
  - /optimizer: adamw.yaml

pooling_class: "icosahedron"
laplacian_type: "combinatorial"

kernel_size: 3
ratio: 1.0
depth: 6
