name: aibedo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cftime=1.5.1.1
  - cudatoolkit=11.3.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - netcdf4=1.5.7
  - numpy=1.21.5
  - pandas=1.3.5
  - pillow=7.2.0
  - pip=21.2.2
  - pygsp=0.5.1
  - python=3.7.13
  - pytorch=1.12.0
  - pytorch-lightning=1.6.4
  - pyyaml=6.0
  - scipy=1.7.3
  - setuptools=59.5.0
  - six=1.16.0
  - tensorboard=2.9.1
  - torchaudio=0.12.0
  - torchmetrics=0.9.2
  - torchvision=0.13.0
  - tqdm
  - xarray=0.20.2
  - yaml=0.2.5
  - pip:
    - hydra-core==1.2.0
    - omegaconf==2.2.2
    - pytorch-ignite==0.4.9
    - timm==0.5.4
    - trimesh==3.12.7
    - wandb==0.12.20

