data_dir: "/work/data/"   # Make sure that it is an absolute path!
input_filename: "compress.isosph.CESM2.historical.r1i1p1f1.Input.Exp8_fixed.nc"
input_vars: [ 'crelSurf_pre', 'crel_pre', 'cresSurf_pre', 'cres_pre', 'netTOAcs_pre', 'lsMask', 'netSurfcs_pre']
output_vars: ['tas_pre', 'psl_pre', 'pr_pre']
batch_size: 10            # batch size for training
eval_batch_size: 512       # batch size for validation, testing (larger might be faster)
num_workers: 0
pin_memory: True
verbose: ${verbose}
seed: 43                # random seed for reproducibility of random data split (different to the one for training)
