monitor: "val/mse"   # which logged value/metric to monitor (used for checkpointing/early stopping/LR scheduling)
mode: "min"          # "min" means higher metric value is better, can also be "max"
loss_weights: [0.0, 0.0, 0.0]
physics_loss_weights: [0.0, 0.0, 0.0, 0.0, 0.0]

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.98
