_target_: aibedo.models.MLP.AIBEDO_MLP

defaults:
  - _self_
  - _base_model_config.yaml   # general, model independent, parameters
  - /optimizer: adamw.yaml

hidden_dims: [1024, 1024, 1024, 1024]  #  [1024, 512, 256]
net_normalization: "layer_norm"
activation_function: "Gelu"
dropout: 0.0
residual: True