data_dir: "/work/data/"   # Make sure that it is an absolute path!
esm_for_training: "CESM2"
ensemble_ids: "any"

input_vars: ['crelSurf_pre', 'crel_pre', 'cresSurf_pre', 'cres_pre', 'netTOAcs_pre', 'lsMask', 'netSurfcs_pre', 'lon', 'lat']
output_vars: ['tas_pre', 'ps_pre', 'pr_pre']
use_crel: True
use_crelSurf: True
use_cresSurf: True

partition: [0.85, 0.15, "era5"] # partition for training, validation, test

time_lag: 0  # horizon of predictions (i.e. how many months ahead to predict)

prediction_data: "same_as_test"

batch_size: 10            # batch size for training
eval_batch_size: 30       # batch size for validation, testing (larger might be faster, but uses more RAM)

num_workers: 0
pin_memory: True
verbose: ${verbose}

seed: 43                # random seed for reproducibility of random data split (different to the one for training)
