IMAGE PARAMS:
  pooling_class: "icosahedron"
  depth: 6
  laplacian_type: "combinatorial"
  time_lag: 0 #dummy for s-convlstm
  time_length: 2 #>=1 for s-convlstm

MODEL PARAMS:
  partition: [0.8,0.1,0.1]
  batch_size: 10
  learning_rate: 0.0001
  n_epochs: 10
  kernel_size: 3

INPUT PARAMS:
  input_file: "/data-ssd/kramea/data_aibedo/compress.isosph.CESM2.historical.r1i1p1f1.Input.Exp8_fixed.nc"
  output_file: "/data-ssd/kramea/data_aibedo/compress.isosph.CESM2.historical.r1i1p1f1.Output.nc"
  output_path: "output_sunet"
  input_vars: ['clivi_pre', 'clwvi_pre', 'crelSurf_pre', 'crel_pre', 'cresSurf_pre', 'cres_pre', 'netTOAcs_pre', 'lsMask', 'netSurfcs_pre', 'lcloud_nonorm']          
  output_vars: ['tas_pre', 'psl_pre', 'pr_pre']
  generation_only: True

EARLY_STOPPING:
  earlystopping_patience: 30
