IMAGE PARAMS:
  pooling_class: "icosahedron"
  depth: 5
  laplacian_type: "combinatorial"
  time_lag: 0 #dummy for s-convlstm
  time_length: 4 #>=1 for s-convlstm

MODEL PARAMS:
  partition: [0.8,0.1,0.1]
  loss_weight: [0.0, 0.0, 1.0, 0.0, 0.0]
  batch_size: 4
  learning_rate: 0.0001
  n_epochs: 5
  kernel_size: 3

INPUT PARAMS:
  input_file: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/compress.isosph5.CESM2.historical.r1i1p1f1.Input.Exp8_fixed.nc"
  output_file: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/compress.isosph5.CESM2.historical.r1i1p1f1.Output.nc"
  output_path: "output_sunet"
  mean_file: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/ymonmean.1980_2010.isosph5.CMIP6.historical.ensmean.Output.nc"
  std_file: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/ymonstd.1980_2010.isosph5.CMIP6.historical.ensmean.Output.nc"
  pe_err: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/CMIP6_PE_clim_err.isoph5.npy"
  pe_std: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/CMIP6_PE_clim_std.isoph5.npy"
  ps_err: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/CMIP6_PS_clim_err.isoph5.npy"
  ps_std: "/data/pmitra/projects/aibedo/sunet/aibedo/skeleton_framework/data/aibedo_data/CMIP6_PS_clim_std.isoph5.npy"
  input_vars: [ 'crelSurf_pre', 'crel_pre', 'cresSurf_pre', 'cres_pre', 'netTOAcs_pre', 'lsMask', 'netSurfcs_pre']
  output_vars: ['tas_pre', 'psl_pre', 'pr_pre']
  loss_vars: ['evspsbl_pre']
  meanstd_vars: ['tas', 'psl', 'pr', 'evspbsl']
  generation_only: True

EARLY_STOPPING:
  earlystopping_patience: 30
