_target_: pytorch_lightning.Trainer

gpus: 1    # -1 for all available GPUs. If you want to use CPU, set to 0.

min_epochs: 1
max_epochs: 15

gradient_clip_val: 2.0

resume_from_checkpoint: null
precision: 32                 # 32 or 16
num_sanity_val_steps: 0       # number of validation steps to execute at the beginning of the training

