IMAGE PARAMS:
  pooling_class: "icosahedron"
  depth: 5
  laplacian_type: "combinatorial"

MODEL PARAMS:
  partition: [0.5,0.3,0.2]
  batch_size: 10
  learning_rate: 0.0002
  n_epochs: 10
  kernel_size: 3

INPUT PARAMS:
  input_file: "/home/ubuntu/aibedo/skeleton_framework/data/Exp_All_CESM2_r1i1p1f1_historical_Input.nc"
  output_file: "/home/ubuntu/aibedo/skeleton_framework/data/Exp_CESM2_r1i1p1f1_historical_Output.nc"
  output_path: "output_sunet"

EARLY_STOPPING:
  earlystopping_patience: 30
