IMAGE PARAMS:
  pooling_class: "icosahedron"
  n_pixels: 10242
  depth: 6
  laplacian_type: "combinatorial"

MODEL PARAMS:
  partition: [0.5,0.3,0.2]
  batch_size: 1
  learning_rate: 0.001
  n_epochs: 30
  kernel_size: 3

SAVING:
  path_to_data: "./data/data_sub/"
  tensorboard_path: "./"
  model_save_path: "./"

DATALOADERS:
  download: True
  means_path: means.npy
  stds_path: stds.npy
  seed: 1

REDUCEONPLATEAU:
  reducelronplateau_mode: "min"
  reducelronplateau_factor: 0.05
  reducelronplateau_patience: 3
STEP:
  steplr_step_size: 30
  steplr_gamma: 0.1

WARMUP:
  warmuplr_warmup_start_value: 0.001
  warmuplr_warmup_end_value: 0.001
  warmuplr_warmup_duration: 1

EARLY_STOPPING:
  earlystopping_patience: 30
